version: '2'

services: 
  jupyter-db:
    build: ../forks/jupyterhub/examples/postgres-checkpoints/db
    env_file:
        - ./env

  jupyter-hub:
    build: ../forks/jupyterhub/examples/postgres-checkpoints/hub
    env_file:
        - ./env
    depends_on:
      - jupyter-db
    links:
      - jupyter-db:postgres
    cap_add:
      - MKNOD
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/fullchain.pem:/etc/certs/ssl.crt:ro
      - ./certs/privkey.pem:/etc/certs/ssl.key:ro
    security_opt:
      - apparmor:unconfined
    ports:
      - "28000:8000"

